# The koura box — the whole machine, declared.
#
# One Hetzner Cloud VM hosting three apps: koura, invoice_sync and kai. Each
# one's systemd units arrive as a flake input from that app's own repo; what
# lives here is everything those units are not — Postgres, Typesense, nginx,
# TLS, the firewall, and the sops secrets each app reads.
#
# None of the three releases is in this closure. They ship into their own Nix
# profiles from their own repos (`bin/deploy-app` in each), so a rebuild here
# never compiles an app and an app deploy never touches the system.
#
# First install: bin/provision (nixos-infect). System updates:
# ./deploy.sh koura.
{ config, lib, pkgs, ... }:
let
  domain = "koura.codecanoe.com";
  # invoice_sync co-hosts here — its own app, its own vhost, same machine.
  invoiceDomain = "invoice.codecanoe.com";
  # kai too. Same deal, plus a Camoufox sidecar (see nixos/kai.nix).
  kaiDomain = "kai.codecanoe.com";
in
{
  # --- Boot / disk ---
  # Bootloader, initrd modules and the root filesystem live in
  # hardware-configuration.nix — generated by nixos-infect (which keeps the
  # Ubuntu image's partition layout) and pulled into the repo by
  # bin/provision. Nothing disk-related is declared here.
  boot.tmp.cleanOnBoot = true;

  # --- Secrets (sops-nix) ---
  # Encrypted blobs live in nixos/secrets/*, committed to the repo and
  # decrypted to /run/secrets/* at activation using the age key placed
  # out-of-band by bin/provision. Edit with `sops nixos/secrets/koura.env`.
  sops = {
    age.keyFile = "/var/lib/sops-nix/age/keys.txt";

    secrets."koura.env" = {
      sopsFile = ../../secrets/koura/koura.env;
      format = "binary";
      # Read by systemd (as root) when starting the koura unit.
      restartUnits = [ "koura.service" ];
    };

    # invoice_sync's env: SECRET_KEY_BASE, the BASIC_AUTH_* pair that locks
    # that site, and its timetracker / eenvoudigfactureren credentials.
    # Edit with `sops nixos/secrets/invoice-sync.env`.
    secrets."invoice-sync.env" = {
      sopsFile = ../../secrets/koura/invoice-sync.env;
      format = "binary";
      restartUnits = [ "invoice-sync.service" ];
    };

    # kai's env: SECRET_KEY_BASE, the BASIC_AUTH_* pair that locks the site,
    # and the Delhaize account the delivery step signs in with.
    # Edit with `sops nixos/secrets/kai.env`.
    secrets."kai.env" = {
      sopsFile = ../../secrets/koura/kai.env;
      format = "binary";
      restartUnits = [ "kai.service" "kai-scraper.service" ];
    };

    secrets."typesense-api-key" = {
      sopsFile = ../../secrets/koura/typesense-api-key;
      format = "binary";
      # Typesense runs with DynamicUser, so hand it the key via the static
      # supplementary group rather than user ownership.
      group = "typesense-secrets";
      mode = "0440";
      restartUnits = [ "typesense.service" ];
    };
  };

  networking.hostName = "koura";
  # DHCP works for every Hetzner Cloud server and survives reattaching a
  # different primary IP (unlike the static config nixos-infect generates).
  networking.useDHCP = true;
  # Pin resolvers so DNS stays stable regardless of what DHCP hands out.
  networking.nameservers = [ "1.1.1.1" "8.8.8.8" ];
  # Only SSH + HTTP(S) are reachable from outside; Postgres and Typesense
  # listen on localhost only and are never opened in the firewall.
  networking.firewall.allowedTCPPorts = [ 22 80 443 ];

  # 4 GB box: a compressed RAM swap is a cheap safety net while Typesense
  # loads its ~500 MB embedding model.
  zramSwap.enable = true;

  time.timeZone = "Europe/Brussels";

  # Hetzner Cloud guest agent — graceful shutdown/reset from the console.
  services.qemuGuest.enable = true;

  # --- Access ---
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
  };
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN4L4FxLZg8uO2bi0wGoJD5IBTOqfxcOGnZIW2FSTrNe klaus@klaus-ThinkPad-X1-Yoga-3rd"
  ];

  # --- Postgres (local, peer-authenticated over the unix socket) ---
  services.postgresql = {
    enable = true;
    package = pkgs.postgresql_16;
    # Matching/search moved to Typesense, but the migration history still
    # contains a CREATE EXTENSION vector — keep pgvector available so a
    # fresh database can replay all migrations.
    extensions = ps: [ ps.pgvector ];
    ensureDatabases = [ "koura" ];
    ensureUsers = [
      {
        name = "koura";
        ensureDBOwnership = true;
      }
    ];
  };
  # CREATE EXTENSION needs superuser, but migrations run as the peer-auth
  # `koura` user. Pre-create it as postgres so the migration's
  # `CREATE EXTENSION IF NOT EXISTS vector` becomes a no-op.
  systemd.services.koura-db-extensions = {
    description = "Ensure Postgres extensions for Koura";
    after = [ "postgresql.service" ];
    requires = [ "postgresql.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      User = "postgres";
      RemainAfterExit = true;
    };
    path = [ config.services.postgresql.package ];
    script = ''
      psql -d koura -c 'CREATE EXTENSION IF NOT EXISTS vector'
    '';
  };
  systemd.services.koura = {
    after = [ "koura-db-extensions.service" ];
    wants = [ "koura-db-extensions.service" ];
  };

  # Nightly pg_dump to /var/backup/postgresql.
  services.postgresqlBackup = {
    enable = true;
    databases = [ "koura" ];
    startAt = "*-*-* 03:15:00";
  };

  # --- Typesense (local search + embedding backend) ---
  # The typesense unit runs with DynamicUser and can't own files
  # declaratively, so the sops secret above is group-readable and we add
  # the unit to that static supplementary group.
  users.groups.typesense-secrets = { };
  systemd.services.typesense.serviceConfig.SupplementaryGroups = [ "typesense-secrets" ];
  services.typesense = {
    enable = true;
    # Same value as TYPESENSE_API_KEY in the app's env file (both come from
    # the same generated key — keep them in sync when rotating).
    apiKeyFile = config.sops.secrets."typesense-api-key".path;
    settings.server = {
      api-address = "127.0.0.1";
      api-port = 8108;
      data-dir = "/var/lib/typesense";
    };
  };

  # --- Koura app ---
  # The release itself is NOT part of this system closure — it's shipped
  # separately via bin/deploy-app into the Nix profile the service module
  # points at. So `bin/deploy` never compiles the app, and shipping app code
  # never rebuilds the system.
  services.koura = {
    enable = true;
    host = domain;
    port = 4000;
    environmentFile = config.sops.secrets."koura.env".path;
  };

  # --- invoice_sync (co-hosted) ---
  # A single-user Phoenix/SQLite app at invoice.codecanoe.com, cheap enough to
  # share this box. Same shape as koura: the release is NOT in this closure —
  # it ships into /nix/var/nix/profiles/invoice-sync via that repo's
  # bin/deploy-app. The module comes from the invoice-sync flake input.
  # Port 4001 because koura holds 4000. See invoice_sync/DEPLOY.md.
  services.invoice-sync = {
    enable = true;
    host = invoiceDomain;
    port = 4001;
    environmentFile = config.sops.secrets."invoice-sync.env".path;
  };

  # --- kai (co-hosted) ---
  # Meal planning against delhaize.be and carrefour.be, at kai.codecanoe.com.
  # Two units rather than one: the Phoenix release on 4002 (4000 and 4001 are
  # taken) and the Camoufox sidecar it prices baskets through, on localhost
  # 8787. Neither release is in this closure — both ship into their own Nix
  # profiles via that repo's bin/deploy-app. See kai/DEPLOY.md.
  #
  # The sidecar is the one thing on this box that can grow without bound: it
  # runs up to two headless Firefoxes. nixos/kai.nix caps it at 1 GB and closes
  # a browser that has gone 15 minutes unused, which is what keeps it a
  # neighbour rather than a problem on a 4 GB machine.
  services.kai = {
    enable = true;
    host = kaiDomain;
    port = 4002;
    environmentFile = config.sops.secrets."kai.env".path;

    # The sidecar shares one Camoufox between both shops (a context each)
    # rather than running one per shop. That is not a detail: two browsers
    # measured ~1.3 GB against this box's ~1.2 GB spare and put it into
    # permanent reclaim — `full avg10=91`, swap 100% used, the sidecar too
    # throttled to answer its own /health. One browser is ~1.0 GB, and the
    # idle reaper hands even that back after ten minutes unused.
    #
    # It still leaves this box with little room. If it starts thrashing
    # again, `scraper.enable = false` gives you back a working kai without
    # prices, and the real fix is a machine with more than 4 GB.
    scraper.enable = true;
  };

  # bin/deploy-app leaves a few profile generations behind for rollback (it
  # trims to the last 5); collect what falls out of them, plus old system
  # generations' build inputs, before the 40 GB disk fills up.
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # `koura-console` — a live IEx shell attached to the running node (the
  # Rails-console equivalent). Sources RELEASE_COOKIE from the sops env and
  # matches the node's loopback distribution settings, so `koura-console`
  # just works over SSH. Root-only: the cookie file is root-readable, and
  # only loopback distribution is reachable (firewall opens 22/80/443).
  environment.systemPackages = [
    (pkgs.writeShellScriptBin "koura-console" ''
      set -eu
      if [ "$(id -u)" -ne 0 ]; then
        echo "koura-console must run as root (it reads /run/secrets/koura.env)." >&2
        exit 1
      fi
      set -a
      . /run/secrets/koura.env
      set +a
      export RELEASE_DISTRIBUTION=sname RELEASE_NODE=koura ERL_EPMD_ADDRESS=127.0.0.1
      export RELEASE_TMP="$(mktemp -d)"
      # Resolve through the app profile so the console always attaches with
      # the *currently deployed* release, even right after a bin/deploy-app.
      exec ${config.services.koura.profile}/bin/koura remote
    '')
  ];

  # --- nginx: HTTPS (Let's Encrypt via security.acme) + reverse proxy ---
  security.acme = {
    acceptTerms = true;
    defaults.email = "klausrubrecht@gmail.com"; # <-- EDIT if desired
  };
  services.nginx = {
    enable = true;
    recommendedProxySettings = true;
    recommendedTlsSettings = true;
    recommendedGzipSettings = true;
    recommendedOptimisation = true;
    virtualHosts.${domain} = {
      enableACME = true;
      forceSSL = true;
      locations."/" = {
        proxyPass = "http://127.0.0.1:4000";
        # Phoenix channels / LiveView need the websocket upgrade headers.
        proxyWebsockets = true;
      };
    };
    # invoice_sync. Its own cert; the app authenticates itself (HTTP Basic,
    # from its sops env), so nothing is gated here.
    virtualHosts.${invoiceDomain} = {
      enableACME = true;
      forceSSL = true;
      locations."/" = {
        proxyPass = "http://127.0.0.1:${toString config.services.invoice-sync.port}";
        proxyWebsockets = true;
      };
    };
    # kai. Same shape — its own cert, HTTP Basic inside the app.
    virtualHosts.${kaiDomain} = {
      enableACME = true;
      forceSSL = true;
      locations."/" = {
        proxyPass = "http://127.0.0.1:${toString config.services.kai.port}";
        proxyWebsockets = true;
      };
    };
  };

  # Set to the release you installed against; do not bump casually.
  system.stateVersion = "25.05";
}
