{ config, lib, pkgs, inputs, ... }:
{
  networking.hostName = "rabbit";
  time.timeZone = "Europe/Brussels";

  # SSH access
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "prohibit-password";
  };

  # Configure sops to use SSH host keys (auto-generated by nixos-anywhere)
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  # Automatically load all trusted SSH keys
  profiles.trustedKeys.enable = true;

  # Enable users with trusted SSH keys
  profiles.users.enable = true;

  # Enable graphical environment
  services.xserver = {
    enable = true;
    desktopManager.xfce.enable = true;
    displayManager.lightdm.enable = true;
  };

  # Base profile
  profiles.base.enable = true;

  # nixbuild.net remote builders
  # services.nixbuild.enable = true;

  # Additional graphical packages
  environment.systemPackages = with pkgs; [
    firefox
    tigervnc
  ];

  # VNC server systemd service
  systemd.services.vncserver = {
    description = "VNC Server";
    after = [ "display-manager.service" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "forking";
      User = "root";
      ExecStart = "${pkgs.tigervnc}/bin/x0vncserver -display :0 -rfbport 5900 -PasswordFile /root/.vnc/passwd -SecurityTypes VncAuth";
      Restart = "on-failure";
    };
  };

  # Open VNC port in firewall
  networking.firewall.allowedTCPPorts = [ 5900 ];
}
