{ config, lib, pkgs, inputs, ... }:
{
  networking.hostName = "rabbit";
  time.timeZone = "Europe/Brussels";

  # SSH access
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "prohibit-password";
  };

  # Configure sops to use SSH host keys (auto-generated by nixos-anywhere)
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  # WireGuard VPN configuration
  sops.secrets.wireguard-rabbit-private-key = {
    sopsFile = ../../secrets/secrets.yaml;
  };

  profiles.wireguard = {
    enable = true;
    address = "10.100.0.2/24";
    privateKeyFile = config.sops.secrets.wireguard-rabbit-private-key.path;
    peers = [
      # Pony temporarily disabled until it's deployed
      # {
      #   name = "pony";
      #   publicKey = "T5ZByh79EAO0YQwr/4Mabi0TrmL81MBZKzeJLaFTdQA=";
      #   allowedIPs = [ "10.100.0.1/32" ];
      #   endpoint = "pony:51820";
      #   persistentKeepalive = 25;
      # }
      {
        name = "client";
        publicKey = "yrduKgtx0oU+OdqknWjavEtxN+yECjUYMTbydxxEGRo=";
        allowedIPs = [ "10.100.0.10/32" ];
        persistentKeepalive = 25;
      }
    ];
  };

  # Firewall: Only SSH and WireGuard publicly accessible
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];  # SSH only
    allowedUDPPorts = [ 51820 ];  # WireGuard
    # RDP and other services only accessible via WireGuard (trusted interface wg0)
  };

  # Automatically load all trusted SSH keys
  profiles.trustedKeys.enable = true;

  # Enable users with trusted SSH keys
  profiles.users.enable = true;

  # Enable graphical environment
  services.xserver = {
    enable = true;
    desktopManager.xfce.enable = true;
    displayManager.lightdm.enable = true;
  };

  # Base profile
  profiles.base.enable = true;

  # nixbuild.net remote builders
  # services.nixbuild.enable = true;

  # Additional graphical packages
  environment.systemPackages = with pkgs; [
    firefox
  ];

  # RDP server configuration
  services.xrdp = {
    enable = true;
    defaultWindowManager = "${pkgs.xfce.xfce4-session}/bin/xfce4-session";
    openFirewall = false;  # RDP only accessible via WireGuard
  };
}
