keys:
  - &admin_klaus: age1sy0ghg9m0r3r5llp843a3nue68d0hr7604upyjrsu9d62sh7usgsplg698
  - &rabbit_host: age12lhqgz30ffvpgcpml3xjp0vfvm3ggdypyknme3jqx3ful6rmsprsvjxytx # Will be updated after nixos-anywhere install
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    -  age:
       - *admin_klaus
       - *rabbit_host
